### ISSUE TITLE
Add install and test process to Contributing section 

### ISSUE THREAD

**Issue by rjaltman** [istanbuljs/puppeteer-to-istanbul#13]
While testing this package does not involve many steps, we should try to eliminate barriers where we can for getting contributors set up on the project. Right now, we have a nice CONTRIBUTING doc written up that outlines our code-of-conduct and general flow (e.g. with PRs), but I feel like the README might benefit from including test and install lines as the main [Istanbul repository](https://github.com/istanbuljs/istanbuljs) has it. What sort of things should we cover in the README and contributing revisions, if any?

**Comment by bcoe** [comment]
@rjaltman this sounds like a good idea to me, want to take a stab at adding some additional content to the README?
